### ISSUE TITLE
Warning email about uncovered date sent even though date was covered

### ISSUE THREAD

**Issue by sherson** [umts/screaming-dinosaur#263]
Hmmmm... I've been getting daily emails about Transit Operations being uncovered (as expected since it's not being used yet), but this morning I also got an email about UMTS IT being uncovered:

> From: transit-it@admin.umass.edu <transit-it@admin.umass.edu>
> Date: Thursday, February 9, 2023 at 4:00 AM
> To: Adam Sherson <sherson@umass.edu>
> Subject: Upcoming dates are uncovered for UMTS IT On-Call
> There are uncovered UMTS IT On-Call dates within the next two weeks. 
> The following dates are uncovered:
> •	09 Feb
> The fallback user is Adam Sherson. 

However, UMTS IT *is* covered:

![umts-it oncall](https://user-images.githubusercontent.com/409008/217885510-4c3b5a1a-f0bc-458e-900c-d0c4349131a0.jpg)

Today is the first day since #259 was deployed that the UMTS IT rotation is switching from one user. Not sure if/how that could be relevant. Will see if it happens again next week.

**Comment by benmelz** [comment]
Definitely relevant:

```ruby
irb(main):013:0> roster.uncovered_dates_between(Date.current, 2.weeks.from_now)
=> []
irb(main):014:0> roster.uncovered_dates_between(Time.zone.now, 2.weeks.from_now)
=> [Thu, 09 Feb 2023]
```

Not sure _exactly_ why yet though

**Comment by benmelz** [comment]
```ruby
irb(main):019:0> Assignment.between(Time.zone.now, 2.weeks.from_now) == Assignment.between(Date.current, 2.weeks.from_now)
=> false
```

The above suggests it's a casting issue here:

https://github.com/umts/screaming-dinosaur/blob/420464bb3daff78c6f9f0f6db685e66d38694636/app/models/assignment.rb#L34-L36

When I look at the actual return values, I'm guessing that when a time is passed instead of a date, its exact value is compared against the date column _at midnight_.

So the solution is one-or-all of
- pass a date object from the job
- cast arguments to dates in `Roster#uncovered_dates_between` before forwarding to `Assignment.between`
- cast arguments to dates in `Assignment.between`

**Comment by benmelz** [comment]
On second thought, I'm thinking that incorporating switchover times in `Assignment.between` might be the "most correct" way to handle this.
